### ISSUE TITLE
BAM file seems to be empty or coverage = 0

### ISSUE THREAD

**Issue by apelin20** [jalvz/depth-cover#2]
Hello,

Log is as follows:
@BioPower3-IBM ~/glomus/mapping/bed_coverage $ java -jar ~/programs/depth-cover/depth-cover.jar -bam ../A1.sort.bam 
01:10:54 - Started.
01:10:54 - 
01:10:57 - No Data to write - BAM file seems to be empty or coverage = 0
01:10:57 - Exiting.
Despite:
@BioPower3-IBM ~/glomus/mapping/bed_coverage $ samtools flagstat ../A1.sort.bam
93629197 + 0 in total (QC-passed reads + QC-failed reads)
922729 + 0 secondary
0 + 0 supplimentary
0 + 0 duplicates
85284613 + 0 mapped (91.09%:-nan%)
92706468 + 0 paired in sequencing
46353234 + 0 read1
46353234 + 0 read2
71168722 + 0 properly paired (76.77%:-nan%)
81637930 + 0 with itself and mate mapped
2723954 + 0 singletons (2.94%:-nan%)
9670322 + 0 with mate mapped to a different chr
6135132 + 0 with mate mapped to a different chr (mapQ>=5)

I used bwa to map my reads, samtools to merge different bam files into one, then samtools to sort it.

Adrian

**Comment by antmarge** [comment]
Hi was there ever a resolution to this? I'm running into the same problem.

**Comment by jalvz** [comment]
Hi, my best guess is that you might have unmapped reads with an actual mapping quality; so the parsing library (Piccard) complains. 
Some people found a way around in this thread: https://www.biostars.org/p/55830/

I hope that helps!
